### ISSUE TITLE
[Coldbox 5.0.0] Lucee 5.2.7+63 MacOS Sierra 10.12.6

### ISSUE THREAD

**Issue by aqualogics** [coldbox-templates/default#10]
Default JavaSettings in Application.cfc raises an error when loading the IBM icu4j-61.1.jar component installed in the /lib directory:

// Default Application.cfc

.......

// Java Integration
	this.javaSettings = { 
		loadPaths = [ ".\lib" ],
		loadColdFusionClassPath = true, 
		reloadOnChange= false 
	};

// Custom loaded classes on ApplicationStart()

public boolean function onApplicationStart(){

application.cbBootstrap = new coldbox.system.Bootstrap( COLDBOX_CONFIG_FILE, COLDBOX_APP_ROOT_PATH, COLDBOX_APP_KEY, COLDBOX_APP_MAPPING );
		application.cbBootstrap.loadColdbox();

 // Instantiate IBM icu4j-61.1 i18n libraries (http://apps.icu-project.org/apiref/icu4j/) 

var Application.Ulocale = createObject("java", "com.ibm.icu.util.ULocale" );
var Application.icu4jTZ = createObject("java", "com.ibm.icu.util.TimeZone");
var Application.Ucalendar = createObject("java", "com.ibm.icu.util.Calendar");
var Application.icu4jDateFormat = createObject("java", "com.ibm.icu.text.DateFormat");
var Application.icu4jDateFormatSymbols = createObject("java", "com.ibm.icu.text.DateFormatSymbols");	
var Application.msgFormat = createObject("java", "com.ibm.icu.text.MessageFormat");
var Application.icu4jCollator = createObject("java", "com.ibm.icu.text.Collator");

return true;
	}

However, when I update to a forward slash from loadPaths = [ ".\lib"] to **loadPaths = [ "./lib"]** in the javaSettings, the jar file is properly picked up and the classes are loaded without error.

NB: in [ColdBox 4.3.0] on adobe engine 2016.0.06+308055, the same default Application.cfc file was working fine and I did not have to modify the javaSettings.

![luceeerrorreport](https://user-images.githubusercontent.com/13482801/41584502-fe4c0e56-73d9-11e8-840d-5939323433ed.png)

**Comment by lmajano** [comment]
That seems more of an engine issue than our template
